### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by eggonzal** [satirama/intersecta#7]
https://github.com/satirama/intersecta/blob/58269a4eb40abb3e7fbf36e2978b0f0b03844ec0/src/index.ts#L135

Excelente documentación, muy profesional, la lib se ve que es fácil de usar y el código super limpio y bien hecho.

Lo único que te podría sugerir es: 

* Cambiar algunos números como el 100 del delay por una variable para que sea más legible y se entienda que representa. 

* Crear unas funciones y variables para quitar comentarios y que el mismo código se explique.

* Cambiar handleInputs por checkOptions o algo que siga siendo consistente con options.

Sólo vi un typo en el README en la descripción de  la opción `once` que debería decir "can't be used"

Muchas felicidades! Tu librería quedó muy profesional con demo y todo!!

**Comment by satirama** [comment]
Todos los puntos que mencionas sin duda mejorarían el código, así que buscaré incorporarlos.
Muchas gracias por el input!

**Comment by eggonzal** [comment]
No de que. Que chido que entraste a esto de la programación y se ve que aprendiste super rápido y con mucha disciplina.

Ya que veo que dominas js, html y css a la perfección dejaré esto por aquí: 
https://www.youtube.com/playlist?list=PLRqwX-V7Uu6bL9VOMT65ahNEri9uqLWfS

Tal vez un día se te ocurra una buena idea innovadora para una extensión web :)

_Edit: Por cierto es la primera vez que veo TypeScript y al ver tu código entendí para qué sirve y me dio curiosidad para empezar a usarlo!_

**Comment by satirama** [comment]
Ya quedó! 
Graciaaaas
